### ISSUE TITLE
Align yaml schema with one used in go-site

### ISSUE THREAD

**Issue by cmungall** [geneontology/contributor-data-pool#1]
In https://github.com/geneontology/go-site/pull/206 we are experimenting with a central set of metadata files for GAFs, GPADs and GPIs.

We might like to have core consortium members manage their metadata in go-site but have an extensible set of external users describe their data using contributor-data-pools in their own repos.

For these to merge we will want to ensure schemas align

**Comment by cmungall** [comment]
Example from mgi.yaml:

```
id: mgi
label: Mouse Genome Informatics
description: "GO data for Mouse Genome Informatics"
datasets:
 -    
   id: mgi.gaf
   label: "mgi gaf file"
   description: "gaf file for mgi from Mouse Genome Informatics"
   url: http://geneontology.org/gene-associations/gene_association.mgi.gz
   type: gaf
   dataset: mgi
   submitter: mgi
   compression: gzip
   source: http://geneontology.org/gene-associations/submissions/gene_association.mgi.gz
   entity_type: 
   status: active
   taxa:
    - NCBITaxon:10090

 -    
   id: mgi.gpad
   label: "mgi gpad file"
   description: "gpad file for mgi from Mouse Genome Informatics"
   url: http://geneontology.org/gpad-gpi/release/mgi.gpa.gz
   type: gpad
   dataset: mgi
   submitter: mgi
   compression: gzip
   source: http://geneontology.org/gpad-gpi/release/submissions/mgi.gpa.gz
   entity_type: 
   status: active
   taxa:
    - NCBITaxon:10090

 -    
   id: mgi.gpi
   label: "mgi gpi file"
   description: "gpi file for mgi from Mouse Genome Informatics"
   url: http://geneontology.org/gpad-gpi/release/mgi.gpi.gz
   type: gpi
   dataset: mgi
   submitter: mgi
   compression: gzip
   source: ftp://ftp.informatics.jax.org/pub/reports/mgi.gpi.gz
   entity_type: 
   status: active
   taxa:
    - NCBITaxon:10090
```
